### ISSUE TITLE
tested live demo(initial load took 12+ seconds) cold start effect? 

### ISSUE THREAD

**Issue by jasan-s** [NickDelfino/nextjs-with-redux-and-cloud-firestore#1]
a subsequent request was close to 1.6seconds even with a disabled cache.

**Comment by NickDelfino** [comment]
Hi Jasan, 

Thanks for the question! 

Yes, the live demo site does cold start when it hasn't been used for a while. Sorry for the delay in site loading but this helps keep costs down!

Hope the example was helpful!

Best,
Nick
